//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyhososinhcap3.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        public byte[] imagest { get; set; }
        public int MaHS { get; set; }
        public string TenHS { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> MaLop { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> Sdt { get; set; }
        public Nullable<double> DiemTB { get; set; }
        public string XepLoai { get; set; }
    
        public virtual Lop Lop { get; set; }
    }
}
