//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyhososinhcap3.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLHSHSSEntities6 : DbContext
    {
        public QLHSHSSEntities6()
            : base("name=QLHSHSSEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DangNhap> DangNhaps { get; set; }
        public virtual DbSet<HocSinh> HocSinhs { get; set; }
        public virtual DbSet<Khoi> Khois { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int AddHocSinh(byte[] imagestt, Nullable<int> mahs, string tenHs, Nullable<int> maLop, string gioiTinh, Nullable<System.DateTime> ngaysinhp, string diaChi, Nullable<int> soDT, Nullable<double> diemHL)
        {
            var imagesttParameter = imagestt != null ?
                new ObjectParameter("imagestt", imagestt) :
                new ObjectParameter("imagestt", typeof(byte[]));
    
            var mahsParameter = mahs.HasValue ?
                new ObjectParameter("mahs", mahs) :
                new ObjectParameter("mahs", typeof(int));
    
            var tenHsParameter = tenHs != null ?
                new ObjectParameter("TenHs", tenHs) :
                new ObjectParameter("TenHs", typeof(string));
    
            var maLopParameter = maLop.HasValue ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(int));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaysinhpParameter = ngaysinhp.HasValue ?
                new ObjectParameter("ngaysinhp", ngaysinhp) :
                new ObjectParameter("ngaysinhp", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var soDTParameter = soDT.HasValue ?
                new ObjectParameter("SoDT", soDT) :
                new ObjectParameter("SoDT", typeof(int));
    
            var diemHLParameter = diemHL.HasValue ?
                new ObjectParameter("DiemHL", diemHL) :
                new ObjectParameter("DiemHL", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddHocSinh", imagesttParameter, mahsParameter, tenHsParameter, maLopParameter, gioiTinhParameter, ngaysinhpParameter, diaChiParameter, soDTParameter, diemHLParameter);
        }
    
        public virtual int AddKhoi(Nullable<int> makhoi, string tenKhoi)
        {
            var makhoiParameter = makhoi.HasValue ?
                new ObjectParameter("makhoi", makhoi) :
                new ObjectParameter("makhoi", typeof(int));
    
            var tenKhoiParameter = tenKhoi != null ?
                new ObjectParameter("TenKhoi", tenKhoi) :
                new ObjectParameter("TenKhoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddKhoi", makhoiParameter, tenKhoiParameter);
        }
    
        public virtual int AddLop(Nullable<int> malop, string tenLop, Nullable<int> maKhoi)
        {
            var malopParameter = malop.HasValue ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(int));
    
            var tenLopParameter = tenLop != null ?
                new ObjectParameter("TenLop", tenLop) :
                new ObjectParameter("TenLop", typeof(string));
    
            var maKhoiParameter = maKhoi.HasValue ?
                new ObjectParameter("MaKhoi", maKhoi) :
                new ObjectParameter("MaKhoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddLop", malopParameter, tenLopParameter, maKhoiParameter);
        }
    
        public virtual int Addngdung(Nullable<int> id, string taikhoan, string matkhau)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("Taikhoan", taikhoan) :
                new ObjectParameter("Taikhoan", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Addngdung", idParameter, taikhoanParameter, matkhauParameter);
        }
    
        public virtual int DeleteHocSinh(Nullable<int> maHs)
        {
            var maHsParameter = maHs.HasValue ?
                new ObjectParameter("MaHs", maHs) :
                new ObjectParameter("MaHs", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteHocSinh", maHsParameter);
        }
    
        public virtual int DeleteKhoi(Nullable<int> maKhoi)
        {
            var maKhoiParameter = maKhoi.HasValue ?
                new ObjectParameter("MaKhoi", maKhoi) :
                new ObjectParameter("MaKhoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteKhoi", maKhoiParameter);
        }
    
        public virtual int DeleteLop(Nullable<int> maLop)
        {
            var maLopParameter = maLop.HasValue ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteLop", maLopParameter);
        }
    
        public virtual int Deletengdung(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Deletengdung", idParameter);
        }
    
        public virtual ObjectResult<GetAllHocSinh_Result> GetAllHocSinh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllHocSinh_Result>("GetAllHocSinh");
        }
    
        public virtual ObjectResult<GetAllKhoi_Result> GetAllKhoi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllKhoi_Result>("GetAllKhoi");
        }
    
        public virtual ObjectResult<GetAllLop_Result> GetAllLop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllLop_Result>("GetAllLop");
        }
    
        public virtual ObjectResult<GetAllngdung_Result> GetAllngdung()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllngdung_Result>("GetAllngdung");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<tmkiemkhoihocsinh_Result> tmkiemkhoihocsinh(string khoihocsinh)
        {
            var khoihocsinhParameter = khoihocsinh != null ?
                new ObjectParameter("khoihocsinh", khoihocsinh) :
                new ObjectParameter("khoihocsinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tmkiemkhoihocsinh_Result>("tmkiemkhoihocsinh", khoihocsinhParameter);
        }
    
        public virtual ObjectResult<tmkiemlophocsinh_Result> tmkiemlophocsinh(string lophocsinh)
        {
            var lophocsinhParameter = lophocsinh != null ?
                new ObjectParameter("lophocsinh", lophocsinh) :
                new ObjectParameter("lophocsinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tmkiemlophocsinh_Result>("tmkiemlophocsinh", lophocsinhParameter);
        }
    
        public virtual ObjectResult<tmkiemmahocsinh_Result> tmkiemmahocsinh(string mahocsinh)
        {
            var mahocsinhParameter = mahocsinh != null ?
                new ObjectParameter("mahocsinh", mahocsinh) :
                new ObjectParameter("mahocsinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tmkiemmahocsinh_Result>("tmkiemmahocsinh", mahocsinhParameter);
        }
    
        public virtual ObjectResult<tmkiemtenhocsinh_Result> tmkiemtenhocsinh(string tenhocsinh)
        {
            var tenhocsinhParameter = tenhocsinh != null ?
                new ObjectParameter("tenhocsinh", tenhocsinh) :
                new ObjectParameter("tenhocsinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tmkiemtenhocsinh_Result>("tmkiemtenhocsinh", tenhocsinhParameter);
        }
    
        public virtual int UpdateHocSinh(byte[] imagestt, Nullable<int> maHs, string tenHs, Nullable<int> maLop, string gioiTinh, Nullable<System.DateTime> ngaysinhp, string diaChi, Nullable<int> soDT, Nullable<double> diemHL, string hocLuc)
        {
            var imagesttParameter = imagestt != null ?
                new ObjectParameter("imagestt", imagestt) :
                new ObjectParameter("imagestt", typeof(byte[]));
    
            var maHsParameter = maHs.HasValue ?
                new ObjectParameter("MaHs", maHs) :
                new ObjectParameter("MaHs", typeof(int));
    
            var tenHsParameter = tenHs != null ?
                new ObjectParameter("TenHs", tenHs) :
                new ObjectParameter("TenHs", typeof(string));
    
            var maLopParameter = maLop.HasValue ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(int));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaysinhpParameter = ngaysinhp.HasValue ?
                new ObjectParameter("ngaysinhp", ngaysinhp) :
                new ObjectParameter("ngaysinhp", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var soDTParameter = soDT.HasValue ?
                new ObjectParameter("SoDT", soDT) :
                new ObjectParameter("SoDT", typeof(int));
    
            var diemHLParameter = diemHL.HasValue ?
                new ObjectParameter("DiemHL", diemHL) :
                new ObjectParameter("DiemHL", typeof(double));
    
            var hocLucParameter = hocLuc != null ?
                new ObjectParameter("HocLuc", hocLuc) :
                new ObjectParameter("HocLuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateHocSinh", imagesttParameter, maHsParameter, tenHsParameter, maLopParameter, gioiTinhParameter, ngaysinhpParameter, diaChiParameter, soDTParameter, diemHLParameter, hocLucParameter);
        }
    
        public virtual int UpdateKhoi(Nullable<int> orinMakhoi, string tenKhoi)
        {
            var orinMakhoiParameter = orinMakhoi.HasValue ?
                new ObjectParameter("OrinMakhoi", orinMakhoi) :
                new ObjectParameter("OrinMakhoi", typeof(int));
    
            var tenKhoiParameter = tenKhoi != null ?
                new ObjectParameter("TenKhoi", tenKhoi) :
                new ObjectParameter("TenKhoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateKhoi", orinMakhoiParameter, tenKhoiParameter);
        }
    
        public virtual int UpdateLop(Nullable<int> maLop, string tenLop, Nullable<int> maKhoi)
        {
            var maLopParameter = maLop.HasValue ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(int));
    
            var tenLopParameter = tenLop != null ?
                new ObjectParameter("TenLop", tenLop) :
                new ObjectParameter("TenLop", typeof(string));
    
            var maKhoiParameter = maKhoi.HasValue ?
                new ObjectParameter("MaKhoi", maKhoi) :
                new ObjectParameter("MaKhoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateLop", maLopParameter, tenLopParameter, maKhoiParameter);
        }
    
        public virtual int Updatengdung(Nullable<int> id, string taikhoan, string matkhau)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("Taikhoan", taikhoan) :
                new ObjectParameter("Taikhoan", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Updatengdung", idParameter, taikhoanParameter, matkhauParameter);
        }
    }
}
